#!/usr/bin/with-contenv bash

shopt -s nullglob

for FILENAME in /run/s6/container_environment/FILE__*; do
    SECRETFILE="$(cat "${FILENAME}")"
    if [[ -f "${SECRETFILE}" ]]; then
        FILESTRIP="${FILENAME//FILE__/}"
        cat "${SECRETFILE}" >"${FILESTRIP}"
        echo "[env-init] ${FILESTRIP##*/} set from ${FILENAME##*/}"
    else
        echo "[env-init] cannot find secret in ${FILENAME##*/}"
    fi
done
